package Connect6;


/**
* Connect6/ServerCorbPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/appcorba/Connect6.idl
* 25 но€бр€ 2017 г. 2:13:33 MSK
*/

public abstract class ServerCorbPOA extends org.omg.PortableServer.Servant
 implements Connect6.ServerCorbOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getColor", new java.lang.Integer (0));
    _methods.put ("getWinner", new java.lang.Integer (1));
    _methods.put ("setMove", new java.lang.Integer (2));
    _methods.put ("getMove", new java.lang.Integer (3));
    _methods.put ("getChanges", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Connect6/ServerCorb/getColor
       {
         int $result = (int)0;
         $result = this.getColor ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // Connect6/ServerCorb/getWinner
       {
         int $result = (int)0;
         $result = this.getWinner ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // Connect6/ServerCorb/setMove
       {
         int player = in.read_long ();
         int _changes[] = Connect6.ServerCorbPackage.intArrayHelper.read (in);
         this.setMove (player, _changes);
         out = $rh.createReply();
         break;
       }

       case 3:  // Connect6/ServerCorb/getMove
       {
         int $result = (int)0;
         $result = this.getMove ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // Connect6/ServerCorb/getChanges
       {
         int $result[] = null;
         $result = this.getChanges ();
         out = $rh.createReply();
         Connect6.ServerCorbPackage.intArrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Connect6/ServerCorb:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerCorb _this() 
  {
    return ServerCorbHelper.narrow(
    super._this_object());
  }

  public ServerCorb _this(org.omg.CORBA.ORB orb) 
  {
    return ServerCorbHelper.narrow(
    super._this_object(orb));
  }


} // class ServerCorbPOA
