package Connect6;

/**
* Connect6/ServerCorbHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/appcorba/Connect6.idl
* 25 но€бр€ 2017 г. 2:13:33 MSK
*/

public final class ServerCorbHolder implements org.omg.CORBA.portable.Streamable
{
  public Connect6.ServerCorb value = null;

  public ServerCorbHolder ()
  {
  }

  public ServerCorbHolder (Connect6.ServerCorb initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Connect6.ServerCorbHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Connect6.ServerCorbHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Connect6.ServerCorbHelper.type ();
  }

}
