package Connect6;


/**
* Connect6/ServerCorbHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/appcorba/Connect6.idl
* 25 но€бр€ 2017 г. 2:13:33 MSK
*/

abstract public class ServerCorbHelper
{
  private static String  _id = "IDL:Connect6/ServerCorb:1.0";

  public static void insert (org.omg.CORBA.Any a, Connect6.ServerCorb that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Connect6.ServerCorb extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Connect6.ServerCorbHelper.id (), "ServerCorb");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Connect6.ServerCorb read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerCorbStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Connect6.ServerCorb value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Connect6.ServerCorb narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Connect6.ServerCorb)
      return (Connect6.ServerCorb)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Connect6._ServerCorbStub stub = new Connect6._ServerCorbStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Connect6.ServerCorb unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Connect6.ServerCorb)
      return (Connect6.ServerCorb)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Connect6._ServerCorbStub stub = new Connect6._ServerCorbStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
