package Connect6.ServerCorbPackage;


/**
* Connect6/ServerCorbPackage/intArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/appcorba/Connect6.idl
* 25 но€бр€ 2017 г. 2:13:33 MSK
*/

public final class intArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public intArrayHolder ()
  {
  }

  public intArrayHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Connect6.ServerCorbPackage.intArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Connect6.ServerCorbPackage.intArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Connect6.ServerCorbPackage.intArrayHelper.type ();
  }

}
